In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

# from gpnotebook.tools.standard_imports import *
import os, re,sys
import yaml
import pandas as pd
import numpy as np

# UCED_P_PDC000441

In [ ]:

file_path = r'F:\GlycoproteinNotebook\search\UCEC_P_PDC000441\step7-expression_matrix\nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv'
df_peptide_2025 = pd.read_csv(file_path, sep='\t')

In [3]:
# 查看前几行
df_peptide_2025.head()

,Sequence,Gene,pool_01,C3L-01840_T_01,C3N-02062_T_01,C3L-02357_T_01,C3N-02437_T_01,C3N-02632_T_01,C3L-05848_T_01,NX021_N_01,...,C3N-01873_T_16,C3N-00750_T_16,C3L-00086_T_16,C3L-01729_T_16,C3L-01355_T_16,C3N-01874_T_16,C3N-00859_T_16,NX037_N_16,C3L-05571_T_16,C3N-02978_T_16
0,AACAVKPQEVQMVNGTITNPINGK-N4H5F0S2G0,ENSP00000349437|IGF2R|2123|24|2136,-1.685647,0.512341,0.506127,-1.645861,0.553636,-1.114802,-0.236711,-0.425551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AACAVKPQEVQMVNGTITNPINGK-N4H5F2S1G0,ENSP00000349437|IGF2R|2123|24|2136,-0.437872,0.798789,0.905996,0.131028,0.980940,-0.317315,1.110452,-0.724487,...,1.492124,1.535672,1.120308,0.142367,1.433214,2.594536,-0.447824,-0.808718,0.0,-0.183516
2,AACAVKPQEVQMVNGTITNPINGK-N4H5F3S1G0,ENSP00000349437|IGF2R|2123|24|2136,0.340634,2.061765,-0.113172,1.254639,1.329464,1.169797,0.029040,0.884302,...,0.702541,0.866555,-0.555142,-0.710193,0.408557,0.338478,-1.243847,-1.055211,0.0,-1.219466
3,AACAVKPQEVQMVNGTITNPINGK-N5H5F1S2G0,ENSP00000349437|IGF2R|2123|24|2136,0.124646,0.630406,1.170945,0.796253,0.183639,0.995370,0.565183,0.281528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AACAVKPQEVQMVNGTITNPINGK-N5H5F3S1G0,ENSP00000349437|IGF2R|2123|24|2136,0.031287,0.875594,1.111723,0.984801,-0.422285,1.331125,1.062451,-1.031711,...,0.757461,-0.136738,2.065567,1.301000,1.733486,-0.773662,NaN,NaN,0.0,1.683402

In [4]:

file_path = r'Z:\glycopeptideatlas\search\gpquest3\UCEC_P_PDC000441\step7-expression_matrix\nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv'
df_peptide_2024 = pd.read_csv(file_path, sep='\t')

In [5]:
df_peptide_2024.head()

,Sequence,Gene,pool_01,C3L-01840_T_01,C3N-02062_T_01,C3L-02357_T_01,C3N-02437_T_01,C3N-02632_T_01,C3L-05848_T_01,NX021_N_01,...,C3N-01873_T_16,C3N-00750_T_16,C3L-00086_T_16,C3L-01729_T_16,C3L-01355_T_16,C3N-01874_T_16,C3N-00859_T_16,NX037_N_16,C3L-05571_T_16,C3N-02978_T_16
0,AACAVKPQEVQMVNGTITNPINGK-N4H5F0S2G0,IGF2R,-1.685647,0.512341,0.506127,-1.645861,0.553636,-1.114802,-0.236711,-0.425551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AACAVKPQEVQMVNGTITNPINGK-N4H5F2S1G0,IGF2R,-0.437872,0.798789,0.905996,0.131028,0.980940,-0.317315,1.110452,-0.724487,...,1.492124,1.535672,1.120308,0.142367,1.433214,2.594536,-0.447824,-0.808718,0.0,-0.183516
2,AACAVKPQEVQMVNGTITNPINGK-N4H5F3S1G0,IGF2R,0.340634,2.061765,-0.113172,1.254639,1.329464,1.169797,0.029040,0.884302,...,0.702541,0.866555,-0.555142,-0.710193,0.408557,0.338478,-1.243847,-1.055211,0.0,-1.219466
3,AACAVKPQEVQMVNGTITNPINGK-N5H5F1S2G0,IGF2R,0.124646,0.630406,1.170945,0.796253,0.183639,0.995370,0.565183,0.281528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AACAVKPQEVQMVNGTITNPINGK-N5H5F3S1G0,IGF2R,0.031287,0.875594,1.111723,0.984801,-0.422285,1.331125,1.062451,-1.031711,...,0.757461,-0.136738,2.065567,1.301000,1.733486,-0.773662,NaN,NaN,0.0,1.683402

In [6]:
result = "sequence_same" if df_peptide_2025.iloc[:, 0].equals(df_peptide_2024.iloc[:, 0]) else "sequence_different"
print(result)

sequence_same

In [8]:
df1_sub = df_peptide_2025.iloc[:, 2:]
df2_sub = df_peptide_2024.iloc[:, 2:]

# 确保列数一致
if df1_sub.shape != df2_sub.shape:
    result = "samples_different"
else:
    # 创建布尔掩码，记录两者是否每个元素都相等（考虑误差）
    comparison = []

    for col in df1_sub.columns:
        s1 = df1_sub[col]
        s2 = df2_sub[col]

        # 两列是否都是数字
        if pd.api.types.is_numeric_dtype(s1) and pd.api.types.is_numeric_dtype(s2):
            # 使用 np.isclose 判断误差小于 1e-6，且同时处理 NaN 比较
            comp = np.isclose(s1, s2, atol=1e-6, equal_nan=True)
        else:
            # 对于非数字型，直接比较是否一致（含 None/NaN）
            comp = (s1.fillna("NA") == s2.fillna("NA"))

        comparison.append(comp)

    # 所有比较都为 True 才返回“是”
    result = "samples_same" if np.all(np.column_stack(comparison)) else "samples_different"

print(result)

samples_same

In [14]:
def compare_dataframes(df1, df2):
    # 检查行数和列数是否相同
    shape,sequence,sampleValues = True,True,True
    if df1.shape != df2.shape:
        shape = False
        print("shape_different")

    # 检查sequence是否相同
    if df1.iloc[:,0].equals(df2.iloc[:,0]):
        print ("sequence_same")
    else:
        sequence = False
        print("seqence_different")

    # 检查每个元素是否相等（考虑误差）
    df1_sub = df1.iloc[:, 2:]
    df2_sub = df2.iloc[:, 2:]
    comparison = []

    for col in df1_sub.columns:
        s1 = df1_sub[col]
        s2 = df2_sub[col]

        # 两列是否都是数字
        if pd.api.types.is_numeric_dtype(s1) and pd.api.types.is_numeric_dtype(s2):
            # 使用 np.isclose 判断误差小于 1e-6，且同时处理 NaN 比较
            comp = np.isclose(s1, s2, atol=1e-6, equal_nan=True)
        else:
            # 对于非数字型，直接比较是否一致（含 None/NaN）
            comp = (s1.fillna("NA") == s2.fillna("NA"))

        comparison.append(comp)

    # 所有比较都为 True 才返回“是”
    if np.all(np.column_stack(comparison)):
        sampleValues = True
        print("SamplesValues same")
    else:
        sampleValues = False
        print("SamplesValues different")
    
    
    if shape and sequence and sampleValues:
        print("dataframes_same")
        return "dataframes_same"

In [12]:
compare_dataframes(df_peptide_2024, df_peptide_2025)

sequence_same
SamplesValues same

'dataframes_same'

In [17]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\UCEC_P_PDC000441\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\UCEC_P_PDC000441\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

# UCEC_P_PDC000126

In [18]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\UCEC_P_PDC000126\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\UCEC_P_PDC000126\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

# UCEC_G_PDC000445

In [19]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\UCEC_G_PDC000445\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\UCEC_G_PDC000445\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

# LUAD_P_PDC000149

In [21]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\LUAD_P_PDC000149\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\LUAD_P_PDC000149\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

# LSCC_P_PDC000232

In [22]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\LSCC_P_PDC000232\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\LSCC_P_PDC000232\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

# HNSCC_P_PDC000222

In [30]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances_2024.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\HNSCC_P_PDC000222\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\HNSCC_P_PDC000222\2024_mspylcoud\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

# GBM_P_PDC000205

In [32]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\GBM_P_PDC000205\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\GBM_P_PDC000205\2024_mspylcoud\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

# CRC_P_PDC000117

In [34]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\CRC_P_PDC000117\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\CRC_P_PDC000117\2024_mspylcoud\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

# CCRCC_P_PDC000128

In [39]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\CCRCC_P_PDC000128\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\CCRCC_P_PDC000128\2024_mspycloud\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same

#  CCRCC_G_PDC000471

In [40]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\CCRCC_G_PDC000471\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\CCRCC_G_PDC000471\2024_mspycloud\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
shape_different
seqence_different

ValueError: operands could not be broadcast together with shapes (104990,) (103571,)

# BRC_P_PDC000121

In [42]:
# compare all 12 files
files_2025= ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"
             ]
files_2024 = ["nglycoform-peptide_matrix-abundances.tsv",
             "nglycoform-peptide_matrix-abundances-MD_norm.tsv",
             "nglycoform-peptide_matrix-intensities.tsv",
             "nglycoform-peptide_matrix-intensities_normalized.tsv",
             "nglycoform-peptide_matrix-log2_ratios.tsv",
             "nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv",
             "nglycoform-site_matrix-abundances.tsv",
             "nglycoform-site_matrix-abundances-MD_norm.tsv",
             "nglycoform-site_matrix-intensities.tsv",
             "nglycoform-site_matrix-intensities_normalized.tsv",
             "nglycoform-site_matrix-log2_ratios.tsv",
             "nglycoform-site_matrix-log2_ratios-MD_norm.tsv"]
for file_2025, file_2024 in zip(files_2025, files_2024):
    file_path_2025 = os.path.join(r'F:\GlycoproteinNotebook\search\BRC_P_PDC000121\step7-expression_matrix', file_2025)
    df_peptide_2025 = pd.read_csv(file_path_2025, sep='\t')

    file_path_2024 = os.path.join(r'Z:\glycopeptideatlas\search\gpquest3\BRC_P_PDC000121\2024_mspycloud\step7-expression_matrix', file_2024)
    df_peptide_2024 = pd.read_csv(file_path_2024, sep='\t')

    print(f"Comparing {file_2025} and {file_2024}:")
    compare_dataframes(df_peptide_2024, df_peptide_2025)

Comparing nglycoform-peptide_matrix-abundances.tsv and nglycoform-peptide_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-abundances-MD_norm.tsv and nglycoform-peptide_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities.tsv and nglycoform-peptide_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-intensities_normalized.tsv and nglycoform-peptide_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios.tsv and nglycoform-peptide_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-peptide_matrix-log2_ratios-MD_norm.tsv and nglycoform-peptide_matrix-log2_ratios-MD_norm_2024.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances.tsv and nglycoform-site_matrix-abundances.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-abundances-MD_norm.tsv and nglycoform-site_matrix-abundances-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities.tsv and nglycoform-site_matrix-intensities.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-intensities_normalized.tsv and nglycoform-site_matrix-intensities_normalized.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios.tsv and nglycoform-site_matrix-log2_ratios.tsv:
sequence_same
SamplesValues same
dataframes_same
Comparing nglycoform-site_matrix-log2_ratios-MD_norm.tsv and nglycoform-site_matrix-log2_ratios-MD_norm.tsv:
sequence_same
SamplesValues same
dataframes_same