In [19]:
path = r"E:\project\LijunChen\PDX\PDX_batch1-7_proteomics\header_expression_matrix.tsv"

In [20]:
import pandas as pd
df = pd.read_csv(path, sep="\t", index_col=0)

In [21]:
df

,126,127N,127C,128N,128C,129N,129C,130N,130C,131,131C
Filename,,,,,,,,,,,
JH_LM1_PDX_Batch2_Global_11112022_set1,PDX new reference_batch2_1,JC0989,MM1727_batch2,CD2089,LS2047,JC1610U,MA0087_batch2,MD1047,MD1124,AM1239,AM1466
JH_LM1_PDX_Batch2_Global_11162022_set2,PDX new reference_batch2_2,MD1451,SB0458,PDX_old_reference_batch2_1,FJ0425,MA0395,SB0466,FJ0573,JC2249,JC2257,JC2258
JH_LM1_PDX_Batch2_Global_11212022_set3,PDX new reference_batch2_3,FJ0585,MD1594_Batch2,CD3359,NCI7_batch2_1,SB0509,CD3382,MA0563,AM1683,CD3454,CD3476
JH_LM1_PDX_Batch2_Global_11252022_set4,PDX new reference_batch2_4,MM0648,MA0805,SB0582,AM1957,MD1049_batch2,MM1039,FJ0908,MA1207,JC2805,SB0753
JH_LM1_PDX_Batch2_Global_11292022_set5,PDX new reference_batch2_5,MA1314,MA1391,MA1508,SB0793,JS0882,CompRef_P93_batch2,MA1611,BTB0630,SB0838,MA1711
...,...,...,...,...,...,...,...,...,...,...,...
JH_LM1_PDX_Batch7_Global_07232025_set4,PDX new reference_batch7_4,MA0853,AM1915,JC2497,MM0859,JC2522,JS0163,JS0182,AM1971,CM1064_batch7,AM2017
JH_LM1_PDX_Batch7_Global_07282025_set5,PDX new reference_batch7_5,MD1963,BTB0496,JS0335,JS0353,SB0711,MA1203,MM1248,FJ1060,CM1212_batch7,NCI-7_batch7_2
JH_LM1_PDX_Batch7_Global_08012025_set6,PDX new reference_batch7_6,ED2497_batch7,CM1214_batch7,CM1233_batch7,CM1277_batch7,JC2901,MA1492,FJ1324,FJ1336,FJ1342,JC2971
JH_LM1_PDX_Batch7_Global_08052025_set7,PDX new reference_batch7_7,FJ1372,CompRef_P94_batch7,JC2990,JS0822,MD2361,JS0918,MM1792,CA0467,MA1765,MM1914
JH_LM1_PDX_Batch7_Global_08092025_set8,PDX new reference_batch7_8,JC3215,CA1867_batch7,ED0196,CM0240,JS1479,CM0264,MA2052,JC3404,CA0891,JC3448

In [22]:
rows = []
import re
for index,row in df.iterrows():
    m = re.search(r'Batch[2-7]', index)
    b = m.group(0) if m else 'Batch1'
    for col in df.columns:
        i = str(row[col]).strip()
        rows.append((i, col, b))
        
df = pd.DataFrame(rows, columns=['case_id', 'channel', 'batch'])

In [23]:
df

                        case_id channel   batch
0    PDX new reference_batch2_1     126  Batch2
1                        JC0989    127N  Batch2
2                 MM1727_batch2    127C  Batch2
3                        CD2089    128N  Batch2
4                        LS2047    128C  Batch2
..                          ...     ...     ...
754                      CM0264    129C  Batch7
755                      MA2052    130N  Batch7
756                      JC3404    130C  Batch7
757                      CA0891     131  Batch7
758                      JC3448    131C  Batch7

[759 rows x 3 columns]

In [24]:
meta_path = r"E:\project\LijunChen\PDX\PDX_batch1-7_proteomics\meta.txt"

In [25]:
df.to_csv(meta_path, sep="\t", index=False)